modLoader = "javafml"
loaderVersion = "[47,)"
license = "${license}"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "${authors}"
description = '''
${description}
'''

[[mixins]]
config = "tacz_caliber_ammo.mixins.json"

[[mixins]]
config = "tacz_caliber_ammo.platform.mixins.json"

[[dependencies.${id}]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "tacz"
mandatory = true
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"
