modLoader = "javafml"
loaderVersion = "[1,)"
license = "${license}"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "${authors}"
description = '''
${description}
'''

[[mixins]]
config = "tacz_caliber_ammo.mixins.json"

[[mixins]]
config = "tacz_caliber_ammo.platform.mixins.json"

[[dependencies.tacz_caliber_ammo]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.233,21.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tacz_caliber_ammo]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.tacz_caliber_ammo]]
modId = "tacz"
type = "required"
versionRange = "[1.1.8-hotfix-r1]"
ordering = "AFTER"
side = "BOTH"